# DXVK needs a shared SDL3 library
if(NOT W3D_BUILD_OPTION_SDL3)
    return()
endif()

if(W3D_ALLOW_MISSING_SDL3)
    find_package(SDL3 COMPONENTS SDL3-shared Headers)
    if(NOT SDL3_FOUND)
        message(WARNING "SDL3 not found — disabling SDL3. Install libsdl3-dev or use setup-sdl in CI.")
        set(W3D_BUILD_OPTION_SDL3 OFF CACHE BOOL "Build OpenW3D with SDL3." FORCE)
        return()
    endif()
else()
    find_package(SDL3 REQUIRED COMPONENTS SDL3-shared Headers)
endif()
